name = "driveflin"
main = "src/index.ts"
compatibility_date = "2024-04-05"

[assets]
directory = "public"

[[d1_databases]]
binding = "DB"
database_name = "jellyfin_db_prod"

# Auto-scan Google Drive libraries every hour
[triggers]
crons = ["0 * * * *"]
